In [1]:
import os
import pickle
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import numpy as np

with open('2018_data_final.pkl' , 'rb') as f:
    data = pickle.load(f)

In [2]:
data.shape

(300, 6)

# A. Count-based Representations

# 1. Term Document Matrix(Frequency based)

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
data['total'] = data['title'] + data['content']
# 제목과 내용을 합쳐서 하나의 Document로 만들어준다.

In [5]:
corpus = data['total'].tolist()
# 전체 Documnet를 이중 리스트로 만들어준다.

In [6]:
corpus[20]

'국민청원 무시하는 이찬열백혜련 국회의원 때려쳐라청원서 놓고 가면 연락 준다더니 캄캄무소식이라 전화했더니   재차 연락한다고 하고 4개월 지났다  국회의원의 맡은바 책무를 무시하는 국회의원은 때려쳐라'

In [8]:
from konlpy.tag import Twitter
twitter = Twitter()

In [9]:
def twitter_tokenizer(x):
    return twitter.morphs(x)

In [10]:
vect = CountVectorizer(tokenizer=twitter_tokenizer, min_df=20, binary = False)
vect.fit(corpus)
# CountVectorizer의 객체를 만들어 갖고 있는 corpus에 대해 Count를 진행한다.
# tokenizer -> 어떤 토크나이져를 쓸 것인가.
# min_df -> 토큰의 최소 빈도수, 20인 경우 20개 미만 등장 토큰은 삭제한다.
# binay = True할 경우 binary Based TDM 이 만들어짐.

CountVectorizer(min_df=20,
                tokenizer=<function twitter_tokenizer at 0x7f8d077e3670>)

In [11]:
TDM = vect.transform(corpus).toarray()

In [12]:
TDM.shape

(300, 314)

In [13]:
TDM

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 3, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
print(corpus[0])
print("*"*100)
print(TDM[0,:])
# 첫번 글에 대한 Document Embedding값은 다음과 같다.

10년 공공임대아파트 분양가산정 방식의 LH 폭리10년을 살고 재산권을 보호해 준다던 취지는 어디가고 청약통장 무효화 거주이동권 박탈 비싼임대료 무주택 강요로 인한 재산권 침해 등을 강요당한 결과가 시세분양입니까 왜 LH는 국민들을 상대로 뻔뻔스런 갭투자를 하는것입니까 국민들은 다주택을 소유하면 세금을 왕창 물리면서 이것이 무슨 합법적인 투기세력인가요 토지를 강제수용해 막대한 차익을 남기는걸로 부족해 땅투기에 이어 아파트 투기까지 하는 행태는 무엇인가요 그럼 우리의 상태도 과거로 되돌려주십시오 10년공임이 이런쓰레기같은 제도였다몃 분양받을 이유가 전혀없으니까요 시세분양할거면 우리가 손해입은 부분을 보상하십시오
****************************************************************************************************
[0 0 0 0 0 0 0 4 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 2 0 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 3 2 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 3 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 1 1 2 0 0 0 0 0 0 1 8 2 3 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [15]:
print(vect.get_feature_names()[30])
print("*"*100)
print(TDM[:,30])
# 교육에 대한 Word Embedding 값은 다음과 같다.

교육
****************************************************************************************************
[0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 1 0 0 0 0 4 1 0 0 0 0 0 0 0 3 0 0 0 0 0 4
 0 0 0 0 0 0 0 0 0 0 2 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 2 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 2 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 7 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0]


# 2. TF-idf

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
tfidf = TfidfVectorizer(tokenizer=twitter_tokenizer, min_df=20).fit(corpus)
tfidf_matrix = tfidf.transform(corpus).toarray()

In [18]:
tfidf_matrix.shape

(300, 314)

In [19]:
tfidf_matrix

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.04723944, 0.17812471, 0.        , ..., 0.        , 0.        ,
        0.05180569],
       ...,
       [0.06835189, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [20]:
print(corpus[0])
print("*"*100)
print(tfidf_matrix[0,:])
# 첫번 글에 대한 Document Embedding값은 다음과 같다.

10년 공공임대아파트 분양가산정 방식의 LH 폭리10년을 살고 재산권을 보호해 준다던 취지는 어디가고 청약통장 무효화 거주이동권 박탈 비싼임대료 무주택 강요로 인한 재산권 침해 등을 강요당한 결과가 시세분양입니까 왜 LH는 국민들을 상대로 뻔뻔스런 갭투자를 하는것입니까 국민들은 다주택을 소유하면 세금을 왕창 물리면서 이것이 무슨 합법적인 투기세력인가요 토지를 강제수용해 막대한 차익을 남기는걸로 부족해 땅투기에 이어 아파트 투기까지 하는 행태는 무엇인가요 그럼 우리의 상태도 과거로 되돌려주십시오 10년공임이 이런쓰레기같은 제도였다몃 분양받을 이유가 전혀없으니까요 시세분양할거면 우리가 손해입은 부분을 보상하십시오
****************************************************************************************************
[0.         0.         0.         0.         0.         0.
 0.         0.21908092 0.         0.         0.         0.11656206
 0.         0.         0.         0.         0.         0.
 0.         0.07693409 0.         0.15440878 0.         0.
 0.18220184 0.         0.         0.         0.         0.
 0.         0.         0.         0.20237431 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.10884146
 0.         0.         0.         0.         0.         0.
 0.    

In [20]:
print(tfidf.get_feature_names()[30])
print("*"*100)
print(tfidf_matrix[:,30])
# 교육에 대한 Word Embedding 값은 다음과 같다.

교육
****************************************************************************************************
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.43599238 0.         0.         0.04046603 0.
 0.         0.         0.         0.36038603 0.27912022 0.
 0.         0.         0.         0.         0.         0.
 0.04947329 0.         0.         0.         0.         0.
 0.25812486 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.0912592
 0.37707017 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.03719525 0.         0.
 0.         0.         0.         0.         0.1188349  0.
 0.11140587 0.         0.         0.         0.         0.
 0.         0.         0.05303991 0.         0.         0.
 0.         0.         0.         0.06502114 0.         0.
 0. 

# B. Document Similarity

needs

In [21]:
class DocSim(object):
    def __init__(self, matrix, idx1, idx2):
        self.matrix = matrix
        self.vector1 = matrix[idx1]
        self.vector2 = matrix[idx2]
        self.a = ((self.vector1 != 0) & (self.vector2 != 0)).sum()
        self.b = ((self.vector1 != 0) & (self.vector2 == 0)).sum()
        self.c = ((self.vector1 == 0) & (self.vector2 != 0)).sum()
        self.d = ((self.vector1 == 0) & (self.vector2 == 0)).sum()
        
    def CFM(self):
        return self.a / (self.a+self.b+self.c+self.d)
    
    def ratio(self):
        return self.a / (self.a+self.b+self.c)
    
    def SMC(self):
        return (self.a+self.d) / (self.a+self.b+self.c+self.d)
    
    def jaccard(self):
        nomin = np.vstack([self.vector1, self.vector2]).min(axis = 0).sum()
        denom = np.vstack([self.vector1, self.vector2]).max(axis = 0).sum()
        return nomin/denom
    
    def overlap_jaccard(self):
        nom = np.vstack([self.vector1, self.vector2]).min(axis = 0).sum()
        denom = min(self.vector1.sum(), self.vector2.sum())
        return nom/denom
    
    def cos_sim(self):
        nom = (self.vector1*self.vector2).sum()
        denom = np.sqrt((self.vector1**2).sum())*np.sqrt((self.vector2**2).sum())
        return nom/denom

In [22]:
corpus[70]

'대학입시 정시수능위주 비중 늘려주세요대학입시 교육정책에 대한 건의입니다 현재 기하급수적으로 수시비중이 대부분을 차지하고 정시수능비중은 적어졌는 추세입니다 그래서 수능으로 대학가기 정말 어려워졌습니다 그러던 와중에 뉴스기사에는 모 교대에 수시 입시 비리가 드러났구요 수시로 대학을 가게되면 각 고등학교 별로 내신시험의 수준이 다르기 때문에 내신시험이 쉬운학교를 갔는학생은 시험이 어려운 학교를 갔는 학생보다 상대적으로 좋은 성적을 받아 대학을 더 잘갈수있습니다 그건 상당히 어떻게 보면 불공평하다고 생각합니다 고등학교진학 또한 본인의 의견보다 부모님 의견으로 원서를 내는 경우도 많으니 말입니다 수능은 그렇게 따지면 같은 공평성을 가진 시험입니다 누구나 같은 난이도의 시험을 치고 통과하여 입시를 치르게 됩니다 그런점에서 더 큰 장점을 가졌다고 생각합니다 수시비중을 낮추고 정시수능위주로 비중을 늘려야한다고 생각합니다 정시 수능위주 비중을 훨씬 더 높일것을 건의합니다'

In [23]:
np.argsort(np.array([DocSim(TDM,70,i).ratio() for i in range(300)]))[::-1][1]

48

In [24]:
corpus[48]

'학생들이 학교가는 것을 좋아하는 대한민국이 되었으면 좋겠습니다저는 대한민국의 국민이자 학생으로써 공교육의 문제를 개선해주기를 바랍니다  올바른 교육은 개인이 적응할 수 있는 유용한 지식과 정보를 제공해주며 사회에서 살아가는 데 기본적인 지식을 제공하는 것입니다  하지만 대한민국이 실행하는 교육은 시험 답안에 기록하고 나면 잊혀지는 휘발성 지식이 대부분이며 한국인의 생활에 필요한 경험이나 지혜 같은 영역은 배제해버렸습니다 그렇기에 현재 대한민국 50대 이하의 세대는 1년 안에 공교육 12년 동안 배워온 지식과 정보 중 95를 자발적으로 잊어버리며 성인으로 살아남기 위해 학원이라는 기관에 들어가 12년 동안 했던 행동을 그대로 반복하고 있습니다 대한민국 교육이 문제가 있음을 증명해주는 것이죠  그렇기에 저는 대한민국의 공교육이 개선되었으면 좋겠습니다 의료나 의복이 개인에 맞춰졌듯이 교육 역시 개인에 맞춰져서 이루어지고 수학이나 영어도 중요할 수 있겠지만 춤이나 농업 역시 중요하고 같은 대우를 받기를 바랍니다 학생들에게 획일화된 교육을 강요하는 행위는 이번 정부가 끝을 내고 학생들의 개성과 능력을 마음껏 펼칠 수 있는 그래서 학생들이 공부를 좋아하고 학교 가는 것을 좋아하는 대한민국이 되었으면 좋겠습니다'

- Common Features Model

- Ratio Model

- Simple Matching Coefficient

- Jaccard Similarity

- Overlap Similarity

- Cos Silmiarity

# C. DL-based Representations

# 1. Word2Vec

### 출처 : https://datascienceschool.net/view-notebook/6927b0906f884a67b0da9310d3a581ee/

In [25]:
data['token'] = data['total'].apply(twitter_tokenizer)
# total 변수에 대한 Tokenizing

In [26]:
sentences = data['token'].tolist()
len(sentences)
# 이중 리스트로 구성 -> gensim input이 이중 리스트임.

300

In [27]:
from gensim.models import Word2Vec, FastText
# input format : [["my", "name", "is", "jamie"], ["jamie", "is", "cute"]]
# size : 임베딩 차원
# window : 윈도우 사이즈
# min_count : 고려할 단어의 최소 빈도 기준
# workers : cpu core 수
# iter : 반복 학습 횟수(epoch)
# sg : 0 -> CBOW, 1 -> Skip-Gram
# CBOW_model - Word2Vec(corpus, size=2, window=2, min_count=2, workers=1, iter=1000, sg=1)

In [28]:
Skip_Gram_model = Word2Vec(sentences, size=100, window=2, min_count=10, workers=8, iter=1000, sg=1)

In [29]:
words = Skip_Gram_model.wv.index2word
words[0]

'을'

In [30]:
vectors = Skip_Gram_model.wv.vectors
vectors[0]

array([ 1.87159792e-01,  1.56222001e-01,  5.37736975e-02, -1.39886349e-01,
        8.47378671e-02,  8.45800340e-02,  1.14998989e-01,  3.61585170e-02,
       -8.16360861e-02, -3.58905196e-01, -1.69312984e-01, -2.22491235e-01,
       -3.34633626e-02,  2.55665127e-02, -5.82186021e-02,  1.21777825e-01,
       -1.59483194e-01,  3.46598355e-03, -1.42611310e-01, -1.41601771e-01,
       -7.73387477e-02, -5.79066873e-02,  7.53284246e-03,  1.63898274e-01,
        3.16757530e-01, -4.66633663e-02,  1.02308400e-01,  1.19538389e-01,
        3.16352338e-01, -4.50879708e-02, -8.19758847e-02,  2.51472369e-02,
        2.29318142e-01, -2.29407817e-01, -2.74340868e-01,  4.36116233e-02,
       -2.25809813e-01, -7.65043199e-02, -1.30300850e-01, -2.81101298e-02,
        4.02584895e-02, -9.38128680e-02, -1.19363302e-02, -1.68556422e-01,
        2.73730516e-01,  2.48158365e-01,  1.76843535e-02,  1.31520843e-02,
       -4.71153893e-02, -8.44982713e-02,  9.62302610e-02,  3.41593742e-01,
       -2.16507509e-01,  

In [31]:
Skip_Gram_model.most_similar("문재인")

[('법안', 0.37732037901878357),
 ('대통령', 0.376155823469162),
 ('먼저', 0.3743467330932617),
 ('순경', 0.37403571605682373),
 ('살인', 0.3711690306663513),
 ('정부', 0.3681146502494812),
 ('각', 0.36672499775886536),
 ('공공', 0.3602352738380432),
 ('물자원', 0.36003902554512024),
 ('2018년', 0.35945695638656616)]

In [32]:
Skip_Gram_model.most_similar("국민")

[('도대체', 0.35624054074287415),
 ('이자', 0.3486241102218628),
 ('적용', 0.3415836989879608),
 ('댄스', 0.3333297073841095),
 ('대한민국', 0.3214092552661896),
 ('산업', 0.320001482963562),
 ('발전', 0.3180534243583679),
 ('조차', 0.31172484159469604),
 ('정의', 0.30960455536842346),
 ('스포츠', 0.30273061990737915)]

In [33]:
Skip_Gram_model_result = dict(zip(words, vectors))

In [34]:
Skip_Gram_model_result['문재인']

array([-0.5334332 ,  0.8310555 ,  0.01583226,  0.44620994,  0.943357  ,
        0.6198858 , -0.02723784, -0.9325878 , -0.9602429 ,  0.16246352,
        0.857442  , -0.12357398,  0.12570786, -0.29322022,  0.4581887 ,
       -0.75370836,  0.76438415, -0.42367873,  0.36018205, -0.8991237 ,
       -0.8783837 ,  0.6905772 , -0.8053484 , -0.09498249,  0.88135976,
       -0.6658481 , -0.42291704,  0.07774981,  0.205868  ,  1.1205765 ,
       -0.06540565,  0.12673871,  0.6535982 , -1.314201  , -0.32977903,
       -0.5946772 , -0.00466897, -0.8639132 ,  0.4287927 , -0.38485718,
       -0.38670275, -0.3762161 ,  0.12899365,  0.20081381,  0.3723275 ,
        1.1898847 , -0.36745813, -1.0009083 ,  0.794783  , -0.08535954,
        0.47168043,  1.0470948 , -0.14723925,  0.44111976,  0.254234  ,
       -0.25632524, -0.5832256 ,  0.11650419,  1.2696695 , -0.00345582,
       -0.7125845 , -1.268519  , -0.20094255,  0.3313288 , -0.42099914,
       -0.9734919 , -0.00843592, -0.22818768,  0.83730006, -0.05

# 2. Fasttext

In [35]:
fasttext_mdoel = FastText(sentences, size=100, window=2, min_count=10, workers=8, iter=1000, sg=1)

In [36]:
words = fasttext_mdoel.wv.index2word
words[0]

'을'

In [37]:
vectors = fasttext_mdoel.wv.vectors
vectors[0]

array([-0.0430058 , -0.05947684, -0.02440167,  0.19318402, -0.00342365,
       -0.01366031, -0.04408166, -0.06417619,  0.07833993,  0.10291204,
       -0.10104584, -0.02925774,  0.05414215, -0.02585179,  0.03913692,
       -0.14573522,  0.02649066,  0.03731516, -0.1326874 ,  0.11438335,
       -0.03309662, -0.11310214, -0.03546644,  0.05822079, -0.0628805 ,
       -0.10859749,  0.00561067, -0.00747285, -0.14682937,  0.03533332,
       -0.13237694,  0.1131288 ,  0.00335164,  0.01610577, -0.10414527,
       -0.0702036 , -0.02958904,  0.01743738, -0.06200908, -0.00823711,
       -0.15479656,  0.08105398,  0.0192868 ,  0.00722217,  0.06126121,
       -0.00534187,  0.0289566 , -0.09636703, -0.07721505, -0.18991435,
       -0.15570518,  0.1695995 ,  0.15843561, -0.1003237 ,  0.06383128,
        0.11340535,  0.08890681, -0.10062777, -0.01923878,  0.05440171,
        0.04602366,  0.10279057,  0.19567946, -0.02937897, -0.02879676,
       -0.0267893 , -0.02031204, -0.03523418, -0.01688569,  0.15

In [38]:
fasttext_mdoel.most_similar("문재인")

[('개헌', 0.47484803199768066),
 ('대통령', 0.4112725257873535),
 ('정부', 0.3923935294151306),
 ('부탁드립니다', 0.38181450963020325),
 ('선거', 0.36150941252708435),
 ('볼셰비키', 0.3586084544658661),
 ('위험', 0.3524147868156433),
 ('내용', 0.345660924911499),
 ('바', 0.3406524658203125),
 ('이번', 0.33628058433532715)]

In [39]:
fasttext_mdoel.most_similar("국민")

[('국가', 0.35415738821029663),
 ('도대체', 0.35212045907974243),
 ('이자', 0.34865713119506836),
 ('해결', 0.3434236943721771),
 ('보조', 0.3341103792190552),
 ('직장', 0.33132022619247437),
 ('권리', 0.3141004741191864),
 ('들', 0.30689680576324463),
 ('발전', 0.3036724328994751),
 ('법안', 0.29622745513916016)]

# 3) Word Embedding X Fasttext

In [40]:
Skip_Gram_model.wv.vectors.shape

(1235, 100)

In [41]:
fasttext_mdoel.wv.vectors.shape

(1235, 100)

In [42]:
ensemble_iookuptable = np.hstack([Skip_Gram_model.wv.vectors,
          fasttext_mdoel.wv.vectors])

ensemble_iookuptable.shape
# Word Embedding X Fasttext look up table

(1235, 200)

# 4) Sentence Embedding using

In [43]:
lookup_dict = dict(zip(words, ensemble_iookuptable))

In [44]:
new = []
for i in sentences:
    inner = list(set(i).intersection(set(words)))
    new.append(inner)

In [45]:
sentence_embbeding = np.zeros(shape = (200,))
for sentence in new:
    embedding = np.zeros(shape = (200,))
    for word in sentence:
        embedding += lookup_dict[word]
    embedding = embedding / len(sentence)
    sentence_embbeding = np.vstack([sentence_embbeding, embedding])
sentence_embbeding = sentence_embbeding[1:,:]

# 5. Doc2vec

In [47]:
!pip install soynlp

     |████████████████████████████████| 416 kB 842 kB/s eta 0:00:01


In [48]:
from soynlp.tokenizer import RegexTokenizer, LTokenizer, MaxScoreTokenizer
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

In [49]:
data["index"] = [str(i) for i in np.arange(len(data))]

In [50]:
from collections import namedtuple
TaggedDocument = namedtuple('TaggedDocument', 'words tags')
tagged_train_docs = [TaggedDocument(d,c) for d, c in data[['token', 'index']].values]
print(len(tagged_train_docs))

300


In [51]:
import multiprocessing
cores = multiprocessing.cpu_count()
cores

12

In [52]:
doc_vectorizer = Doc2Vec(
    dm=0,            # PV-DBOW / default 1
    dbow_words=1,    # w2v simultaneous with DBOW d2v / default 0
    window=8,        # distance between the predicted word and context words
    size=100,        # vector size
    alpha=0.025,     # learning-rate
    seed=1234,
    min_count=10,    # ignore with freq lower
    min_alpha=0.025, # min learning-rate
    workers=cores)   # multi cpu
    #hs = 1,          # hierarchical softmax / default 0
    #negative = 10,   # negative sampling / default 5)

In [53]:
tagged_train_docs

[TaggedDocument(words=['10년', '공공', '임대', '아파트', '분양', '가', '산정', '방식', '의', 'LH', '폭리', '10년', '을', '살', '고', '재산권', '을', '보호', '해', '준다던', '취지', '는', '어디가', '고', '청약', '통장', '무효', '화', '거주', '이', '동권', '박탈', '비싼', '임대료', '무', '주택', '강요', '로', '인한', '재산권', '침해', '등', '을', '강요', '당', '한', '결과', '가', '시', '세', '분양', '입', '니까', '왜', 'LH', '는', '국민', '들', '을', '상대로', '뻔뻔스런', '갭', '투자', '를', '하는것', '입', '니까', '국민', '들', '은', '다', '주택', '을', '소유', '하면', '세금', '을', '왕창', '물리면서', '이', '것', '이', '무슨', '합법', '적', '인', '투기', '세력', '인가요', '토지', '를', '강제', '수', '용해', '막대', '한', '차익', '을', '남기', '는걸', '로', '부족해', '땅', '투기', '에', '이어', '아파트', '투기', '까지', '하는', '행태', '는', '무엇', '인가요', '그럼', '우리', '의', '상태', '도', '과거', '로', '되돌려주십시오', '10년', '공임이', '이런', '쓰레기', '같은', '제도', '였다', '몃', '분양', '받을', '이유', '가', '전혀', '없으니까', '요', '시세', '분', '양할거면', '우리', '가', '손해', '입은', '부분', '을', '보상', '하십시오'], tags='0'),
 TaggedDocument(words=['군인', '이', '민간', '병원', '에서', '치료', '를', '받아도', '보상', '받을수', '있게', '해주세요', '군인

In [54]:
doc_vectorizer.build_vocab(tagged_train_docs)
print(str(doc_vectorizer))

Doc2Vec(dbow+w,d100,n5,w8,mc10,s0.001,t12)


In [55]:
import time
from tqdm import tnrange
start_time = time.time()

for epoch in tnrange(10):
    doc_vectorizer.train(tagged_train_docs, total_examples=doc_vectorizer.corpus_count, epochs=doc_vectorizer.iter)
    doc_vectorizer.alpha -= 0.002 # decrease the learning rate
    doc_vectorizer.min_alpha = doc_vectorizer.alpha # fix the learning rate, no decay

print("start_time", start_time) 
print("--- %s seconds ---" %(time.time() - start_time))


start_time 1596740320.925026
--- 3.580932855606079 seconds ---


In [56]:
X = np.array([doc_vectorizer.infer_vector(doc.words) for doc in tagged_train_docs])
y = np.array([int(doc.tags) for doc in tagged_train_docs])

In [57]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

In [58]:
data.iloc[70]['content']

'대학입시 교육정책에 대한 건의입니다 현재 기하급수적으로 수시비중이 대부분을 차지하고 정시수능비중은 적어졌는 추세입니다 그래서 수능으로 대학가기 정말 어려워졌습니다 그러던 와중에 뉴스기사에는 모 교대에 수시 입시 비리가 드러났구요 수시로 대학을 가게되면 각 고등학교 별로 내신시험의 수준이 다르기 때문에 내신시험이 쉬운학교를 갔는학생은 시험이 어려운 학교를 갔는 학생보다 상대적으로 좋은 성적을 받아 대학을 더 잘갈수있습니다 그건 상당히 어떻게 보면 불공평하다고 생각합니다 고등학교진학 또한 본인의 의견보다 부모님 의견으로 원서를 내는 경우도 많으니 말입니다 수능은 그렇게 따지면 같은 공평성을 가진 시험입니다 누구나 같은 난이도의 시험을 치고 통과하여 입시를 치르게 됩니다 그런점에서 더 큰 장점을 가졌다고 생각합니다 수시비중을 낮추고 정시수능위주로 비중을 늘려야한다고 생각합니다 정시 수능위주 비중을 훨씬 더 높일것을 건의합니다'

In [59]:
A_sparse = sparse.csr_matrix(X)
similarities = cosine_similarity(A_sparse)

In [60]:
np.argsort(similarities[70,:])[::-1][1]

163

In [61]:
data.iloc[163]['content']

'누구를 위한 수시며 학생부종합전형입니디까 지방학생전형 있는데  지역균형을 위해 수시가 필요하다니요 정시로 공정하게 대학갑시다 아이들 수능못봐도 부모잘둬서 학종으로 대학 잘가네요 말이나 되나요'